### PR TITLE
DOMA-4630 reset property map viewMode on section remove

### PR DESCRIPTION
**Pull request by sitozzz**
When remove last section/parking from property map `viewMode` will not changed.

After:

https://user-images.githubusercontent.com/25844927/201318372-f0a0dda2-a319-408d-b930-873ed3225a47.mov

Before:

https://user-images.githubusercontent.com/25844927/201318548-174bcdde-ad67-4565-a558-0c16c429e598.mov

### CODE REVIEW

**Comment by AntonAL** [comment]
In description of this PR, video for "After" should be for "Before"

**Comment by AntonAL** [comment]
If we delete last parking, will we see sections?

**Review by AntonAL — APPROVED** [review]

**Review by Alllex202 — APPROVED** [review]

**Comment by sitozzz** [comment]
> If we delete last parking, will we see sections?

Yup)

**Comment by sitozzz** [comment]
> In description of this PR, video for "After" should be for "Before"

You are correct, fixed description

**Pull request merged**
