### PR TITLE
fix(condo): DOMA-8950 typo at meter filters

### PR DESCRIPTION
**Pull request by sitozzz**
- [x] update callcenter submodule -> https://github.com/open-condo-software/condo_call_center/pull/192

### CODE REVIEW

**Review by nomerdvadcatpyat — APPROVED** [review]

**Review by toplenboren — APPROVED** [review]

**Comment by Alllex202** [comment]
It was also great to fix existing saved templates

**Comment by sitozzz** [comment]
> It was also great to fix existing saved templates

Done that, please check my solution for that problem

**Review by nomerdvadcatpyat — APPROVED** [review]
Will you update cc in this pr?

**Comment by sitozzz** [comment]
> Will you update cc in this pr?
Yes, I'll do it

**Review by Alllex202 — APPROVED** [review]

**Review by toplenboren — APPROVED** [review]

**Pull request merged**
