### PR TITLE
DOMA-3978 fix empty contact/property Page

### PR DESCRIPTION
**Pull request by VKislov**
before: 
Screenshot 2022-08-22 at 18 46 53

after: 
Screenshot 2022-08-22 at 17 49 12

### CODE REVIEW

**Comment by pahaz** [comment]
image
You can't use random generated class names as the source of true.

**Review by sitozzz — COMMENTED** [review]
Why not just to make button prop optional at this component?

**Comment by sitozzz** [comment]
> image
> 
> You can't use random generated class names as the source of true.

Also this doesn't work, find another solution

**Comment by VKislov** [comment]
> Why not just to make button prop optional at this component?

Because the entire property page is imported from the condo. Adding a prop to a nested component will require dragging in unnecessary and non-obvious logic for condos

**Review by sitozzz — APPROVED** [review]

**Comment by nomerdvadcatpyat** [comment]
pls do not merge submodule branches into master/main until you have passed the review in condo

**Review by nomerdvadcatpyat — APPROVED** [review]

**Pull request merged**
