### PR TITLE
SBERDOMA-1039 Fix corrupt migration directory

### PR DESCRIPTION
**Pull request by toplenboren**
Fixes corrupt migration directory, that was resulted in `not` rebasing #481 after #490 merge to master

@MrFoxPro ^^

### CODE REVIEW

**Comment by MrFoxPro** [comment]
I think it is better to regenerate your migration script instead of creating this empty one

**Comment by toplenboren** [comment]
> I think it is better to regenerate your migration script instead of creating this empty one

We think that any migration that is in master is already applied to some stand

So to prevent further directory corruption we generate new migration instead of deleting the last one and creating new. We may discuss this further

**Comment by MrFoxPro** [comment]
> 
> 
> > I think it is better to regenerate your migration script instead of creating this empty one
> 
> We think that any migration that is in master is already applied to some stand
> 
> So to prevent further directory corruption we generate new migration instead of deleting the last one and creating new. We may discuss this further

no, it is not applied, because migration check was failed

**Comment by MrFoxPro** [comment]
My suggestion: 
Delete `apps/condo/migrations/20210823153807-0047_merge_0046_auto_20210819_1407_0046_auto_20210820_1328.js`
run `makemigrations`
populate it with this:

```js

// auto generated by kmigrator
// KMIGRATOR:0047_auto_20210823_1552:IyBHZW5lcmF0ZWQgYnkgRGphbmdvIDMuMi42IG9uIDIwMjEtMDgtMjMgMTA6NTINCg0KaW1wb3J0IGRqYW5nby5jb250cmliLnBvc3RncmVzLmZpZWxkcy5qc29uYg0KZnJvbSBkamFuZ28uZGIgaW1wb3J0IG1pZ3JhdGlvbnMsIG1vZGVscw0KDQoNCmNsYXNzIE1pZ3JhdGlvbihtaWdyYXRpb25zLk1pZ3JhdGlvbik6DQoNCiAgICBkZXBlbmRlbmNpZXMgPSBbDQogICAgICAgICgnX2RqYW5nb19zY2hlbWEnLCAnMDA0Nl9hdXRvXzIwMjEwODIwXzEzMjgnKSwNCiAgICBdDQoNCiAgICBvcGVyYXRpb25zID0gWw0KICAgICAgICBtaWdyYXRpb25zLkFkZEZpZWxkKA0KICAgICAgICAgICAgbW9kZWxfbmFtZT0nYmlsbGluZ2ludGVncmF0aW9uJywNCiAgICAgICAgICAgIG5hbWU9J2RhdGFGb3JtYXQnLA0KICAgICAgICAgICAgZmllbGQ9ZGphbmdvLmNvbnRyaWIucG9zdGdyZXMuZmllbGRzLmpzb25iLkpTT05GaWVsZChibGFuaz1UcnVlLCBudWxsPVRydWUpLA0KICAgICAgICApLA0KICAgICAgICBtaWdyYXRpb25zLkFkZEZpZWxkKA0KICAgICAgICAgICAgbW9kZWxfbmFtZT0nYmlsbGluZ2ludGVncmF0aW9uaGlzdG9yeXJlY29yZCcsDQogICAgICAgICAgICBuYW1lPSdkYXRhRm9ybWF0JywNCiAgICAgICAgICAgIGZpZWxkPWRqYW5nby5jb250cmliLnBvc3RncmVzLmZpZWxkcy5qc29uYi5KU09ORmllbGQoYmxhbms9VHJ1ZSwgbnVsbD1UcnVlKSwNCiAgICAgICAgKSwNCiAgICAgICAgbWlncmF0aW9ucy5BbHRlckZpZWxkKA0KICAgICAgICAgICAgbW9kZWxfbmFtZT0nYmlsbGluZ3JlY2VpcHQnLA0KICAgICAgICAgICAgbmFtZT0naW1wb3J0SWQnLA0KICAgICAgICAgICAgZmllbGQ9bW9kZWxzLlRleHRGaWVsZCh1bmlxdWU9VHJ1ZSksDQogICAgICAgICksDQogICAgXQ0K

exports.up = async (knex) => {
    await knex.raw(`
    BEGIN;

--

-- Add field dataFormat to billingintegration

--

ALTER TABLE "BillingIntegration" ADD COLUMN "dataFormat" jsonb NULL;

--

-- Add field dataFormat to billingintegrationhistoryrecord

--

ALTER TABLE "BillingIntegrationHistoryRecord" ADD COLUMN "dataFormat" jsonb NULL;

--

-- Alter field importId on billingreceipt

--

ALTER TABLE "BillingReceipt" ALTER COLUMN "importId" SET NOT NULL;

ALTER TABLE "BillingReceipt" ADD CONSTRAINT "BillingReceipt_importId_9da6acbf_uniq" UNIQUE ("importId");

CREATE INDEX "BillingReceipt_importId_9da6acbf_like" ON "BillingReceipt" ("importId" text_pattern_ops);

COMMIT;


    `)
}

exports.down = async (knex) => {
    await knex.raw(`
    BEGIN;
--
-- Truncate all rows on billingReceipts (made intentionally by toplenboren)
--
TRUNCATE TABLE "BillingReceipts";
--
-- Alter field importId on billingreceipt
--
ALTER TABLE "BillingReceipt" ALTER COLUMN "importId" DROP NOT NULL;
DROP INDEX IF EXISTS "BillingReceipt_importId_9da6acbf_like";
--
-- Add field dataFormat to billingintegrationhistoryrecord
--
ALTER TABLE "BillingIntegrationHistoryRecord" DROP COLUMN "dataFormat" CASCADE;
--
-- Add field dataFormat to billingintegration
--
ALTER TABLE "BillingIntegration" DROP COLUMN "dataFormat" CASCADE;
COMMIT;


    `)
}
```

**Comment by toplenboren** [comment]
> My suggestion:
> Delete `apps/condo/migrations/20210823153807-0047_merge_0046_auto_20210819_1407_0046_auto_20210820_1328.js`
> and `apps/condo/migrations/20210819190726-0046_auto_20210819_1407.js`
> run `makemigrations` and then
> populate new migration file with this:
> 
> ```js
> /* autogenerated hash here */
> exports.up = async (knex) => {
>     await knex.raw(`
>     BEGIN;
> 
> --
> 
> -- Add field dataFormat to billingintegration
> 
> --
> 
> ALTER TABLE "BillingIntegration" ADD COLUMN "dataFormat" jsonb NULL;
> 
> --
> 
> -- Add field dataFormat to billingintegrationhistoryrecord
> 
> --
> 
> ALTER TABLE "BillingIntegrationHistoryRecord" ADD COLUMN "dataFormat" jsonb NULL;
> 
> --
> 
> -- Alter field importId on billingreceipt
> 
> --
> 
> ALTER TABLE "BillingReceipt" ALTER COLUMN "importId" SET NOT NULL;
> 
> ALTER TABLE "BillingReceipt" ADD CONSTRAINT "BillingReceipt_importId_9da6acbf_uniq" UNIQUE ("importId");
> 
> CREATE INDEX "BillingReceipt_importId_9da6acbf_like" ON "BillingReceipt" ("importId" text_pattern_ops);
> 
> COMMIT;
> 
> 
>     `)
> }
> 
> exports.down = async (knex) => {
>     await knex.raw(`
>     BEGIN;
> --
> -- Truncate all rows on billingReceipts (made intentionally by toplenboren)
> --
> TRUNCATE TABLE "BillingReceipts";
> --
> -- Alter field importId on billingreceipt
> --
> ALTER TABLE "BillingReceipt" ALTER COLUMN "importId" DROP NOT NULL;
> DROP INDEX IF EXISTS "BillingReceipt_importId_9da6acbf_like";
> --
> -- Add field dataFormat to billingintegrationhistoryrecord
> --
> ALTER TABLE "BillingIntegrationHistoryRecord" DROP COLUMN "dataFormat" CASCADE;
> --
> -- Add field dataFormat to billingintegration
> --
> ALTER TABLE "BillingIntegration" DROP COLUMN "dataFormat" CASCADE;
> COMMIT;
> 
> 
>     `)
> }
> ```

This would be nice and will work, but if the process is wrong we should change process, not only current case

**Pull request closed without merging**
