### PR TITLE
INFRA add API token for amplitude

### PR DESCRIPTION
**Pull request by sitozzz**

### CODE REVIEW

**Review by dkoviazin — APPROVED** [review]

**Comment by pahaz** [comment]
You also need to set up the development env.

**Comment by pahaz** [comment]
How to test it on the development stand?

**Comment by sitozzz** [comment]
> How to test it on the development stand?

I will add this to the config in the new PR

**Comment by sitozzz** [comment]
> How to test it on the development stand?

I will add this to the config in the new PR

**Pull request closed without merging**
