### PR TITLE
Hotfix SBERDOMA-476 Make OrganizationEmployeeRole.description not required, fix LocalizedText resolving by migrator

### PR DESCRIPTION
**Pull request by MrFoxPro**

### CODE REVIEW

**Review by AntonAL — COMMENTED** [review]
You cannot change migration (nor file name, nor content), once it was merged to master, because it was already applied to database.
You can only make a new migration.

**Review by pahaz — CHANGES_REQUESTED** [review]
migration is already! in MASTER you cant remove it!

**Comment by MrFoxPro** [comment]
@AntonAL , @pahaz , this migration wasn't applied to db.

**Comment by pahaz** [comment]
Omg 😱

**Review by Dimitreee — APPROVED** [review]

**Review by pahaz — APPROVED** [review]

**Pull request merged**
