### PR TITLE
feat(dev-portal): INFRA-243 stricter icon requirements

### PR DESCRIPTION
**Pull request by SavelevMatthew**
## Before

image

## After

https://github.com/open-condo-software/condo/assets/50069872/59b54866-b1fc-4a51-b727-d4fe927125d8

### CODE REVIEW

**Review by Alllex202 — APPROVED** [review]
What about the size limit in bytes? 
Can we add it to the description?

**Comment by toplenboren** [comment]
It is best to provide templates for icon too. In png / svg format. So they can easily import it to their editing tool

**Comment by SavelevMatthew** [comment]
> What about the size limit in bytes?
> Can we add it to the description?

I don't think so, 1mb is more than enough for any png in specified size and this limits are flexible. Size and color limits are strict, so we need to specify it explicitly

**Comment by SavelevMatthew** [comment]
> It is best to provide templates for icon too. In png / svg format. So they can easily import it to their editing tool

Ty for awesome advice. Added a link to our style guides 👍

**Pull request merged**
