### PR TITLE
DOMA-2927 fixed the width of the columns in the table on the employee…

### PR DESCRIPTION
**Pull request by Alllex202**
… view page

### CODE REVIEW

**Comment by toplenboren** [comment]
before, after?

**Review by toplenboren — APPROVED** [review]

**Comment by Alllex202** [comment]
> before, after?

just changed default table to custom table

**Comment by Alllex202** [comment]
> before, after?

the main changes were here
https://github.com/open-condo-software/condo/pull/1943

**Comment by Alllex202** [comment]
> > before, after?
> 
> the main changes were here #1943

but I had to roll back the changes on the scroll :(, because the designer has no rule for very large tables with a sufficiently small screen

**Comment by Alllex202** [comment]
And it seems to me that this pull request will be superfluous, because. in one of the other pull requests I did the same
https://github.com/open-condo-software/condo/pull/2003/files#diff-bcd14f5e0a10748773ef9b16134566420a8044c407e123dc335b47df98725329

**Review by akarjakin — APPROVED** [review]

**Pull request closed without merging**
